[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'mg979/vim-visual-multi'

