[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'connorholyday/vim-snazzy'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'rhysd/clever-f.vim'

