[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'connorholyday/vim-snazzy'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = 'release/rpc'

