[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'Shatur/neovim-ayu'

[[plugins]]
repo = 'connorholyday/vim-snazzy'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
rev = 'release/rpc'

[[plugins]]
repo = 'mg979/vim-visual-multi'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'romgrk/barbar.nvim'
depends = ['lewis6991/gitsigns.nvim', 'nvim-tree/nvim-web-devicons']
rev = '^1.0.0'

[[plugins]]
repo = 'monaqa/dial.nvim'

