[tools]
"aqua:codex" = "latest"
"cargo:atuin" = "latest"
bat = "latest"
"cargo:sushidesu/dotmux" = "latest"
"cargo:sushidesu/kitchen-cli" = "latest"
duckdb = "latest"
"cargo:exa" = "latest"
jq = "latest"
"pipx:git-filter-repo" = "latest"
zellij = "latest"
neovim = "latest"
zoxide = "latest"
lazygit = "latest"
tmux = "latest"
